apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/acm-operator/

patches:
  - target:
      kind: Subscription
      name: advanced-cluster-management
    path: patch-channel.yaml
