---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/aap-hub/

patches:
  - patch: |-
      - op: replace
        path: /spec/href
        value: https://automation-hub-ansible-automation-platform.apps.liberation.mountain.expektorans.de
    target:
      kind: ConsoleLink
      name: automation-hub