apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: example-keycloak
  namespace: keycloak
spec:
  hostname:
    strict: false
    strictBackchannel: false
    hostname: patch-me
  http:
    httpEnabled: true
  ingress:
    className: openshift-default
  instances: 1