apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: example-keycloak
  namespace: keycloak
spec:
  hostname:
    strict: false
    strictBackchannel: false
    hostname: example-keycloak-keycloak.apps.liberation.mountain.expektorans.de
  http:
    tlsSecret: keycloak-example-tls-secret
  ingress:
    className: openshift-default
  instances: 1